name: Kubernetes - Deploy a YAML manifest
description: Deploys a YAML manifest to a Kubernetes cluster.
inputs:
  config:
    description: Base64 encoded KubeConfig file
    required: true
  manifest:
    description: YAML manifest file path
    required: true
    default: deployment.yaml
  namespace:
    description: Delete resources in the specified namespace
    required: true
  deleteByLabel:
    description: Delete resources labelled with the given label (key=value)
    required: true
runs:
  using: "composite"
  steps:
    - uses: azure/setup-kubectl@v2.0
      with:
        version: "v1.22.7"
    - name: Set Kube Config
      shell: bash
      run: |
        mkdir -p ~/.kube
        echo ${{ inputs.config }} | base64 --decode > ~/.kube/config
        kubectl version
    - name: Delete existing resources
      shell: bash
      run: kubectl delete all,ingress -l ${{ inputs.deleteByLabel }} -n ${{ inputs.namespace }}
    - name: Create Deployment
      shell: bash
      run: kubectl apply -f ${{ inputs.manifest }}