name: Docker - Login, Build, and Push Image
description: Login to Registry, Build Image from Dockerfile in the current directory, and Push Image to the Registry
inputs:
  registry:
    description: Docker registry host (e.g. us.gcr.io)
    required: true
  username:
    description: Docker registry username
    required: true
  password:
    description: Docker registry password
    required: true
  tag:
    description: Tag to use for the image
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Build & Push Docker Image
      uses: docker/build-push-action@v2.10.0
      with:
        context: .
        push: true
        tags: ${{ inputs.tag }}